language: julia
os:
  - osx
  - linux
julia:
  - nightly
  - 0.4
notifications:
  email: true
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("GazeDispersion"); Pkg.test("GazeDispersion"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("Example")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
